[package]
name = "qv"
description = "quickly view your data"
version = "0.1.24"
edition = "2021"
homepage = "https://github.com/timvw/qv"
repository = "https://github.com/timvw/qv"
readme = "README.md"
authors = ["Tim Van Wassenhove <tim@timvw.be>"]
license = "Apache-2.0"
keywords = [ "quickview", "data", "query", "sql", "datafusion" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
camino = "1.0.9"
clap = { version = "3.1.18", features = ["derive"] }
datafusion = { version = "8.0.0", features = ["avro"] }
datafusion-objectstore-s3 = "0.2.1"
#deltalake = { path = "../delta-rs/rust", features = ["datafusion-ext", "s3"]  }
deltalake = { git = "https://github.com/delta-io/delta-rs", features = ["datafusion-ext", "s3"] }
futures-util = "0.3.21"
tokio = "1.19"
url = "2.2.2"
