[package]
name = "qv"
description = "quickly view your data"
version = "0.1.27"
edition = "2021"
homepage = "https://github.com/timvw/qv"
repository = "https://github.com/timvw/qv"
readme = "README.md"
authors = ["Tim Van Wassenhove <tim@timvw.be>"]
license = "Apache-2.0"
keywords = [ "quickview", "data", "query", "sql", "datafusion" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
aws-config = "0.48"
aws-types = "0.48"
chrono = "0.4.22"
clap = { version = "3.2.22", features = ["derive"] }
datafusion = { version = "12.0.0", features = ["avro"] }
deltalake = { git = "https://github.com/delta-io/delta-rs", features = ["datafusion-ext", "s3-rustls"] }
futures = "0.3"
glob = "0.3.0"
itertools = "0.10"
object_store = { version = "0.5.0", features = ["aws"] }
tokio = { version = "1.21", features = ["macros", "rt", "rt-multi-thread", "sync", "parking_lot"] }
url = "2.3"
